POST  http://localhost:8000/api/ofertas HTTP/1.1
Accept: application/json
Content-Type: application/json

{
    "idCuentaEnviar" : 1,
    "idCuentaRecibir": 3,
    "idJuegoPorEnviar" : 2,
    "idJuegoPorRecibir" : 1,
    "estado" : "pendiente"
}
